### PR TITLE
Create tests for functions that will check ftp:// prefix

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
# Description

Adds a feature to limit the viewable directory structure in Globus. Currently, when you are viewing the content of a Globus collection using the Globus web app, everything within the path is viewable. It remains to be seen if this function is still necessary. I believe that the request will still need to be processed by the core service and arango because what is viewable will be determined by what user is trying to access what on the machine.

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
@par-hermes format

**Comment by JoshuaSBrown** [comment]
@par-hermes format

**Comment by JoshuaSBrown** [comment]
@par-hermes format

**Review by nedvedba — APPROVED** [review]
Looks good to me, code is clean and well commented so it is very easy to follow.

**Pull request closed without merging**
